//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableTap.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableTap.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the menu.
        /// </summary>
        public static string accessToMenu {
            get {
                return ResourceManager.GetString("accessToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Menu.
        /// </summary>
        public static string AddMenu_Button {
            get {
                return ResourceManager.GetString("AddMenu_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Menu Title.
        /// </summary>
        public static string AddNewMenu_Title {
            get {
                return ResourceManager.GetString("AddNewMenu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Dashboard.
        /// </summary>
        public static string adminDashboard {
            get {
                return ResourceManager.GetString("adminDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage system data, monitor requests and update menus..
        /// </summary>
        public static string AdminDashboard_Description {
            get {
                return ResourceManager.GetString("AdminDashboard_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Dashboard.
        /// </summary>
        public static string AdminDashboard_Subtitle {
            get {
                return ResourceManager.GetString("AdminDashboard_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Dashboard.
        /// </summary>
        public static string AdminDashboard_Title {
            get {
                return ResourceManager.GetString("AdminDashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Navigation .
        /// </summary>
        public static string AdminNavigation {
            get {
                return ResourceManager.GetString("AdminNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string allRightsReserved {
            get {
                return ResourceManager.GetString("allRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic service at a small price with more expensive options for more customizations..
        /// </summary>
        public static string basicServiceAtSmallPrice {
            get {
                return ResourceManager.GetString("basicServiceAtSmallPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Careers.
        /// </summary>
        public static string careers {
            get {
                return ResourceManager.GetString("careers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, the client can only use the browser to access the menu..
        /// </summary>
        public static string clientUseBrowser {
            get {
                return ResourceManager.GetString("clientUseBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Scheme.
        /// </summary>
        public static string colorScheme {
            get {
                return ResourceManager.GetString("colorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string contactUs {
            get {
                return ResourceManager.GetString("contactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies.
        /// </summary>
        public static string cookies {
            get {
                return ResourceManager.GetString("cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost savings.
        /// </summary>
        public static string costSavings {
            get {
                return ResourceManager.GetString("costSavings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a QR Code.
        /// </summary>
        public static string createQR {
            get {
                return ResourceManager.GetString("createQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join many of establishments already using TableTap to enhance their dining experience..
        /// </summary>
        public static string ctaSectionDescription {
            get {
                return ResourceManager.GetString("ctaSectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Transform Your Establishment?.
        /// </summary>
        public static string ctaSectionHeading {
            get {
                return ResourceManager.GetString("ctaSectionHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers can access the menu via QR code easily without downloading an app..
        /// </summary>
        public static string customersAccessQR {
            get {
                return ResourceManager.GetString("customersAccessQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer satisfaction.
        /// </summary>
        public static string customerSatisfaction {
            get {
                return ResourceManager.GetString("customerSatisfaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers use their phones to scan the code and access the digital menu instantly..
        /// </summary>
        public static string customersUsePhones {
            get {
                return ResourceManager.GetString("customersUsePhones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        public static string customize {
            get {
                return ResourceManager.GetString("customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital menu platform for establishments. Create and share menus via QR codes..
        /// </summary>
        public static string digitalMenuPlatform {
            get {
                return ResourceManager.GetString("digitalMenuPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinks.
        /// </summary>
        public static string Drinks {
            get {
                return ResourceManager.GetString("Drinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ease of access.
        /// </summary>
        public static string EaseAccess {
            get {
                return ResourceManager.GetString("EaseAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can the menu be easily customized?.
        /// </summary>
        public static string easilyCustomized {
            get {
                return ResourceManager.GetString("easilyCustomized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚀 Easy, fast, and sustainable..
        /// </summary>
        public static string easyFast {
            get {
                return ResourceManager.GetString("easyFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email us:.
        /// </summary>
        public static string emailUs {
            get {
                return ResourceManager.GetString("emailUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environmental protection.
        /// </summary>
        public static string environmentalProtection {
            get {
                return ResourceManager.GetString("environmentalProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌍 Jump into your establishment&apos;s digital future..
        /// </summary>
        public static string establishmentDigitalFuture {
            get {
                return ResourceManager.GetString("establishmentDigitalFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishment Name.
        /// </summary>
        public static string EstablishmentName {
            get {
                return ResourceManager.GetString("EstablishmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Styles.
        /// </summary>
        public static string exploreStyles {
            get {
                return ResourceManager.GetString("exploreStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilities.
        /// </summary>
        public static string Facilities {
            get {
                return ResourceManager.GetString("Facilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string faq {
            get {
                return ResourceManager.GetString("faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say goodbye to repeated printing — save ongoing menu costs for your restaurant..
        /// </summary>
        public static string Feature_CostSaving_Desc {
            get {
                return ResourceManager.GetString("Feature_CostSaving_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Saving.
        /// </summary>
        public static string Feature_CostSaving_Title {
            get {
                return ResourceManager.GetString("Feature_CostSaving_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers can access the menu via QR code easily without downloading an app..
        /// </summary>
        public static string Feature_EasyAccess_Desc {
            get {
                return ResourceManager.GetString("Feature_EasyAccess_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy Access.
        /// </summary>
        public static string Feature_EasyAccess_Title {
            get {
                return ResourceManager.GetString("Feature_EasyAccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce paper use and contribute to your restaurant’s environmental sustainability..
        /// </summary>
        public static string Feature_EcoFriendly_Desc {
            get {
                return ResourceManager.GetString("Feature_EcoFriendly_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eco-Friendly.
        /// </summary>
        public static string Feature_EcoFriendly_Title {
            get {
                return ResourceManager.GetString("Feature_EcoFriendly_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo uploads for each dish.
        /// </summary>
        public static string featureMenuItem1 {
            get {
                return ResourceManager.GetString("featureMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe or ingredient details for each item.
        /// </summary>
        public static string featureMenuItem2 {
            get {
                return ResourceManager.GetString("featureMenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and update your menu items, categories, and prices with ease..
        /// </summary>
        public static string featureMenuManagementDescription {
            get {
                return ResourceManager.GetString("featureMenuManagementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Management.
        /// </summary>
        public static string featureMenuManagementHeading {
            get {
                return ResourceManager.GetString("featureMenuManagementHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsive design.
        /// </summary>
        public static string featureMobileItem1 {
            get {
                return ResourceManager.GetString("featureMobileItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast loading times.
        /// </summary>
        public static string featureMobileItem2 {
            get {
                return ResourceManager.GetString("featureMobileItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No app download required.
        /// </summary>
        public static string featureMobileItem3 {
            get {
                return ResourceManager.GetString("featureMobileItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beautiful menus that look great on any device, especially smartphones..
        /// </summary>
        public static string featureMobileOptimizedDescription {
            get {
                return ResourceManager.GetString("featureMobileOptimizedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Optimized.
        /// </summary>
        public static string featureMobileOptimizedHeading {
            get {
                return ResourceManager.GetString("featureMobileOptimizedHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate unique QR codes for each table that link directly to your digital menu..
        /// </summary>
        public static string featureQrCodeDescription {
            get {
                return ResourceManager.GetString("featureQrCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code Menus.
        /// </summary>
        public static string featureQrCodeHeading {
            get {
                return ResourceManager.GetString("featureQrCodeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited QR code generation.
        /// </summary>
        public static string featureQRCodeItem1 {
            get {
                return ResourceManager.GetString("featureQRCodeItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category-specific codes.
        /// </summary>
        public static string featureQRCodeItem2 {
            get {
                return ResourceManager.GetString("featureQRCodeItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printable high-resolution files.
        /// </summary>
        public static string featureQRCodeItem3 {
            get {
                return ResourceManager.GetString("featureQRCodeItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything you need to create and manage digital menus for your establishment..
        /// </summary>
        public static string featuresSectionDescription {
            get {
                return ResourceManager.GetString("featuresSectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features Designed for Establishments.
        /// </summary>
        public static string featuresSectionHeading {
            get {
                return ResourceManager.GetString("featuresSectionHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        public static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a QR code for your establishment that you can print and place on tables or display on screens..
        /// </summary>
        public static string getQR {
            get {
                return ResourceManager.GetString("getQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string getStarted {
            get {
                return ResourceManager.GetString("getStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sleek digital solution for present your menu online in an eco-friendly and efficient way.
        /// </summary>
        public static string Hero_Subtitle {
            get {
                return ResourceManager.GetString("Hero_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitize your establishment menu now with TableTap.
        /// </summary>
        public static string Hero_Title {
            get {
                return ResourceManager.GetString("Hero_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create beautiful digital menus, share them via QR codes, and give your customers a seamless experience..
        /// </summary>
        public static string heroDescription {
            get {
                return ResourceManager.GetString("heroDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Menus for Modern Establishments.
        /// </summary>
        public static string heroHeading {
            get {
                return ResourceManager.GetString("heroHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string homePage {
            get {
                return ResourceManager.GetString("homePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does TableTap work?.
        /// </summary>
        public static string howTableTapWork {
            get {
                return ResourceManager.GetString("howTableTapWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Login Credentials.
        /// </summary>
        public static string InvalidLoginCredentials {
            get {
                return ResourceManager.GetString("InvalidLoginCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal.
        /// </summary>
        public static string legal {
            get {
                return ResourceManager.GetString("legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Name.
        /// </summary>
        public static string MenuName {
            get {
                return ResourceManager.GetString("MenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Type.
        /// </summary>
        public static string MenuType {
            get {
                return ResourceManager.GetString("MenuType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly visit to the lists.
        /// </summary>
        public static string monthlyVisit {
            get {
                return ResourceManager.GetString("monthlyVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Active Plan .
        /// </summary>
        public static string MostActivePlan {
            get {
                return ResourceManager.GetString("MostActivePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Nav_Contact {
            get {
                return ResourceManager.GetString("Nav_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string Nav_FAQ {
            get {
                return ResourceManager.GetString("Nav_FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Nav_Features {
            get {
                return ResourceManager.GetString("Nav_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How It Works.
        /// </summary>
        public static string Nav_HowItWorks {
            get {
                return ResourceManager.GetString("Nav_HowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        public static string Nav_Stats {
            get {
                return ResourceManager.GetString("Nav_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Requests .
        /// </summary>
        public static string PlanRequests {
            get {
                return ResourceManager.GetString("PlanRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans.
        /// </summary>
        public static string Plans {
            get {
                return ResourceManager.GetString("Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string pricing {
            get {
                return ResourceManager.GetString("pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the plan that works best for your establishment..
        /// </summary>
        public static string pricingSectionDescription {
            get {
                return ResourceManager.GetString("pricingSectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple, Transparent Pricing.
        /// </summary>
        public static string pricingSectionHeading {
            get {
                return ResourceManager.GetString("pricingSectionHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string privacy {
            get {
                return ResourceManager.GetString("privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce paper usage and contribute to the environmental sustainability of your establishment..
        /// </summary>
        public static string reducePaperUsage {
            get {
                return ResourceManager.GetString("reducePaperUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered establishment.
        /// </summary>
        public static string registeredEstablishment {
            get {
                return ResourceManager.GetString("registeredEstablishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register your establishment on the platform and start adding your listing easily..
        /// </summary>
        public static string registerYourEstablishment {
            get {
                return ResourceManager.GetString("registerYourEstablishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string registration {
            get {
                return ResourceManager.GetString("registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Plan.
        /// </summary>
        public static string RequestedPlan {
            get {
                return ResourceManager.GetString("RequestedPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting Establishments Title.
        /// </summary>
        public static string RequestingEstablishments_Title {
            get {
                return ResourceManager.GetString("RequestingEstablishments_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default.
        /// </summary>
        public static string resetToDefault {
            get {
                return ResourceManager.GetString("resetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say goodbye to repetitive printing and save your establishment the periodic costs of lists..
        /// </summary>
        public static string sayGoodbye {
            get {
                return ResourceManager.GetString("sayGoodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔒 Secure and without the need for any app..
        /// </summary>
        public static string secureWithoutApp {
            get {
                return ResourceManager.GetString("secureWithoutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Option.
        /// </summary>
        public static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Establishments .
        /// </summary>
        public static string SharedEstablishments {
            get {
                return ResourceManager.GetString("SharedEstablishments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do I need a special app?.
        /// </summary>
        public static string specialApp {
            get {
                return ResourceManager.GetString("specialApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features of TableTap.
        /// </summary>
        public static string TableTapFeatures {
            get {
                return ResourceManager.GetString("TableTapFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is TableTap free?.
        /// </summary>
        public static string tableTapFree {
            get {
                return ResourceManager.GetString("tableTapFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableTap numbers.
        /// </summary>
        public static string tableTapNumbers {
            get {
                return ResourceManager.GetString("tableTapNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string terms {
            get {
                return ResourceManager.GetString("terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Customizer.
        /// </summary>
        public static string themeCustomizer {
            get {
                return ResourceManager.GetString("themeCustomizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Requests .
        /// </summary>
        public static string TotalRequests {
            get {
                return ResourceManager.GetString("TotalRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Dashboard.
        /// </summary>
        public static string userDashboard {
            get {
                return ResourceManager.GetString("userDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Pricing.
        /// </summary>
        public static string viewPricing {
            get {
                return ResourceManager.GetString("viewPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Why Choose TableTap? .
        /// </summary>
        public static string whyChoose {
            get {
                return ResourceManager.GetString("whyChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, you can edit and add items whenever you want via the Dashboard..
        /// </summary>
        public static string youCanEdit {
            get {
                return ResourceManager.GetString("youCanEdit", resourceCulture);
            }
        }
    }
}
